from __future__ import annotations

import logging
from typing import Any, Dict

log = logging.getLogger(__name__)

_client = None

_MODEL_WATERFALL = [
    "gemini-2.0-flash",
    "gemini-2.0-flash-lite",
    "gemini-2.5-flash-lite",
    "gemini-2.5-flash",
]


def _get_client():
    global _client
    if _client is not None:
        return _client

    from ..settings import get_gemini_api_key
    key = get_gemini_api_key()
    if not key:
        raise RuntimeError(
            "GEMINI_API_KEY is not set. Add it to your .env file or environment variables."
        )

    from google import genai
    _client = genai.Client(api_key=key)
    return _client


def _generate_with_fallback(prompt: str, *, max_output_tokens: int = 1024, temperature: float = 0.3) -> str:
    """Try each model in the waterfall until one succeeds."""
    client = _get_client()
    from google.genai import types
    last_exc: Exception | None = None
    for model_name in _MODEL_WATERFALL:
        try:
            response = client.models.generate_content(
                model=model_name,
                contents=prompt,
                config=types.GenerateContentConfig(
                    max_output_tokens=max_output_tokens,
                    temperature=temperature,
                ),
            )
            log.info("Gemini model used: %s", model_name)
            return response.text.strip()
        except Exception as exc:
            log.warning("Model %s failed: %s — trying next.", model_name, exc)
            last_exc = exc
    raise RuntimeError(f"All Gemini models failed. Last error: {last_exc}") from last_exc


def generate_explanation(context: Dict[str, Any]) -> str:
    prompt = (
        "You are a digital forensics expert for a major sports media agency. "
        "A computer vision system has flagged the following image as a potential "
        "unauthorized copy. Here is the forensic evidence:\n\n"
        f"  - Detected transformation: {context.get('mutation_type', 'Unknown')}\n"
        f"  - Perceptual hash (pHash) similarity: {context.get('phash_score', 0)}%\n"
        f"  - ORB keypoint match ratio: {context.get('orb_score', 0)}%\n"
        f"  - Combined weighted similarity score: {context.get('combined_score', 0)}%\n"
        f"  - System classification: {context.get('authenticity_label', 'Unknown')}\n\n"
        "In 3-4 sentences, explain: (1) what specific manipulation was likely applied "
        "to the original image, (2) why the mathematical evidence supports this conclusion, "
        "and (3) what this means from a copyright infringement perspective. "
        "Use professional but accessible language suitable for a rights holder."
    )

    text = _generate_with_fallback(prompt, max_output_tokens=512, temperature=0.3)
    log.info("Gemini generated explanation (%d chars)", len(text))
    return text


def generate_dmca_text(context: Dict[str, Any]) -> str:
    prompt = (
        "You are a senior legal agent for a sports broadcasting network. "
        "Draft a complete, formal DMCA takedown notice under 17 U.S.C. § 512(c) "
        "using the following case evidence. The notice must include all 6 standard "
        "DMCA sections: (1) Identification of the copyright owner, (2) Identification "
        "of the copyrighted work, (3) Identification of the infringing material and its "
        "location, (4) Contact information, (5) Good-faith belief statement, and "
        "(6) Accuracy and authority statement with electronic signature.\n\n"
        "CASE EVIDENCE:\n"
        f"  - Copyright owner: {context.get('owner_name', '[Rights Holder]')}\n"
        f"  - Owner contact: {context.get('owner_email', '[email@example.com]')}\n"
        f"  - Original asset registered in DigiWarden Vault at: {context.get('registered_at', 'Unknown')}\n"
        f"  - Infringing material found at URL: {context.get('source_url', '[URL not captured]')}\n"
        f"  - Combined similarity score: {context.get('similarity_score', 0)}%\n"
        f"  - Perceptual hash (pHash) match: {context.get('phash_score', 'N/A')}%\n"
        f"  - ORB keypoint match: {context.get('orb_score', 'N/A')}%\n"
        f"  - Detected image manipulation: {context.get('mutation_type', 'Unknown')}\n\n"
        "The mathematical fingerprint evidence (pHash + ORB keypoint analysis) "
        "was generated by the DigiWarden Content Genome system and constitutes "
        "forensic proof of derivation. Reference this evidence explicitly in section 3. "
        "Be formal, legally precise, and professional throughout."
    )

    text = _generate_with_fallback(prompt, max_output_tokens=1024, temperature=0.2)
    log.info("Gemini generated DMCA notice (%d chars)", len(text))
    return text


def extract_keywords_vision(image_bytes: bytes, mime_type: str) -> str:
    client = _get_client()
    from google.genai import types

    prompt = (
        "You are analyzing a sports photograph for a copyright tracking system. "
        "Describe the specific event or scene in exactly 5 search keywords. "
        "Example output: 'Virat Kohli century celebration IPL 2024'. "
        "Return ONLY the keywords, nothing else, no punctuation."
    )

    response = client.models.generate_content(
        model=_MODEL_WATERFALL[0],
        contents=[
            types.Part.from_bytes(data=image_bytes, mime_type=mime_type),
            prompt,
        ],
    )
    keywords = response.text.strip()
    log.info("Gemini Vision extracted keywords: %s", keywords)
    return keywords
